### ISSUE TITLE
unsupported data source

### ISSUE THREAD

**Issue by vijay39119** [openlandmap/spatial-layers#1]
Hi,
I successfully added the ensembled DTM for the first time into QGIS, however when I close the program or the raster file and attempt to reload it, I have the following problem.
Unsupported Data Source: /vsicurl/https://s3.eu-central-1.wasabisys.com/openlandmap/dtm/dtm.bareearth_ensemble_std_30m_s_2018_go_epsg4326_v20230210.tif is not a supported raster data source. 
Not only me, I have tried the same in others systems also. Everyone is facing the same issue

**Comment by yu-feng-ho** [comment]
Hi, @vijay39119,

The version has been changed. Sorry we did not update for a while. Please access the data from here https://s3.eu-central-1.wasabisys.com/openlandmap/dtm/dtm.bareearth_ensemble_std_30m_s_2018_go_epsg4326_v20230221.tif instead.
